### ISSUE TITLE
Allow user to disable notifications

### ISSUE THREAD

**Issue by guhemama** [guhemama/worpdress-comment-reply-email-notification#1]
From Wordpress.org:

> Is there a way to disable email notifications if the commenter subscribes to comments? Otherwise they get two emails (which is a bit spammy) regarding the same comment.

Implement it in a per-comment and global basis.

**Comment by colinchan89** [comment]
Hey man did you ever look into building this enhancement? Your plug-in is so close to being perfect for what I need, the only thing it's missing is a checkbox to opt-in to receiving the email. I'm going to try and develop this myself but I'm not very experienced with WordPress, so if you have any tips for how to accomplish this, I would really appreciate it! Otherwise, I will let you know how it goes! Thanks!

**Comment by guhemama** [comment]
Hey Colin, I was actually planning on implementing this on Jan 2017, haha. I was going to implement it as opt-out only, but your comment made me rething my approach - it should be opt-in and allow the customer to opt-out any time.

TBH, I'm not very experienced with Wordpress too, but I expect it to involve these steps: adding a hook to render the checkbox on the comment form; adding a hook to persit the client's choice when the comment is submitted; adding an unsubscribe link to the notification email; creating a new table to persist the client's choice (when he opts-in; a new table may not be necessary but it could be good for performance).

Suggestions? ;)

**Comment by colinchan89** [comment]
I got it working pretty simply. We use the Timber templating plug-in, so I added an <input> type="checkbox" to the comment form with name="comment_subscribe_opt_in".

In the plug-in, above the first condition:
`if ($comment->comment_approved == 1 && $comment->comment_parent > 0)`
I added this:
`    if (isset($_POST['comment_subscribe_opt_in']) && $_POST['comment_subscribe_opt_in'] == 'on'){
      add_comment_meta($comment_id, 'comment_subscribe_opt_in', $_POST['comment_subscribe_opt_in']);
    }`

and then inside the original condition I added this:
`      $parent = get_comment($comment->comment_parent);
        $parent_id = $comment_parent->comment_ID;
        $parent_metadata = get_comment_meta($parent_id, 'comment_subscribe_opt_in', true);
        if(isset($parent_metadata) && $parent_metadata == 'on'){`

So it only fires the email notification if you opt-in by clicking the checkbox. And it only applies to that single comment. So on the same blog post, the same user can opt in to receiving notifications for a certain comment, and opt-out of another. I have no plans on implementing any way to manage your subscriptions. But with my use case, the only person who can reply to a comment is a Wordpress admin, so it doesn't need to be very complicated.

**Comment by guhemama** [comment]
Thanks for the great feedback

**Comment by guhemama** [comment]
Something weird just happened with my comment, lol.

Anyway, thanks for sharing your solution @colinchan89 !

I've just updated the plugin, and used a hook to _automagically_ render the checkbox. :)
