### ISSUE TITLE
Updates for GDPR Laws

### ISSUE THREAD

**Issue by joelrendall** [guhemama/worpdress-comment-reply-email-notification#17]
It would be great add/adjust the following:

1) Allow an option to add an additional checkbox to be added for user to consent to collecting and storing information on the form, which will be a requirement for the GDPR laws coming into effect in the EU in May. (It's a drag, but necessary)

Example: 
√ I consent to mysite.com collecting and storing the information I submit in this form. <Privacy policy link>

2) Disable the "subscribe" checkbox by default, another GDPR requirement.

Example:

![image](https://user-images.githubusercontent.com/8376419/39085708-8e4be056-457e-11e8-9730-b7fe21c00f56.png)

Thanks!! :)

**Comment by guhemama** [comment]
Hey Joel,

1. It makes sense. I'm already adding some options to the admin interface, and it'd be simple to add another one.
2. Already on the roadmap. :)

- Gustavo

**Comment by joelrendall** [comment]
Awesome, thanks so much! Let me know if you need help testing and/or would appreciate a donation towards development. Cheers

**Comment by guhemama** [comment]
Thanks Joel! Commits and beer donations are welcome, lol.

Jokes aside, I have some spare time this week, and since GDPR is already law, I will try to get this done ASAP.

**Comment by joelrendall** [comment]
Sounds great! Feel free to send PayPal address or similar so I can show my appreciation since I’m using this a business site ;)

**Comment by joelrendall** [comment]
Hahaha adorei a referência portuguesa 😂Como é que falas português europeu se no teu perfil diz que és de Asución? Thanks for the donation link (which I've put to use), and for the very useful plugin!

**Comment by guhemama** [comment]
@joelrendall 

Thanks for the donation, and I'm glad you like the plugin! Also, suggestions and complaints are always welcome.

Respondendo: sou brasileiro, bastou adicionar _tuga sprinkles_ no meu português brasileiro hahuahua. BTW, loved your website and the project - the lessons are pretty cool!

**Comment by joelrendall** [comment]
Haha thanks, glad you like! I'm sure you got a chuckle from the "desculpem brasileiros" on the homepage. A couple people have been offended in the past but it's kind of a joke based on the fact that European Portuguese is much less prominent online than Brazilian (which is more widely available, for learning materials)

**Comment by guhemama** [comment]
I actually lolled :rofl: I totally get it, and you guys did carve a nice niche from this... Congrats! :D
