### ISSUE TITLE
Subscription checkbox

### ISSUE THREAD

**Issue by Patdundee** [guhemama/worpdress-comment-reply-email-notification#20]
Hi Guys
There is no option to disable and remove the Subscribe to comment checkbox. The word subscribe makes normal people think they have to pay. For those that do undertsnad what it means, it forces them to subscribe if they wish to comment. Not eveyone wishes to do this, or have this option showing all the time.

In wordpress all comments are held for modification and this option is not needed. 
How can i prevent this option from being displayed (The same as you have the option for the new GDPR checkbox to show or hide)

Many thanks

**Comment by guhemama** [comment]
Hey Pat,

Thanks for using tve plugin. Currently you csn use a filter to change the checkbox label, but soon I will release an update with a filter that will allow your to change the entire checkbox HTML - you could then change it to a hidden input that would work like a checked checkbox (the subscription only occurs if the element value is found on the $_POST global).
