### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by junglesub** [guhemama/worpdress-comment-reply-email-notification#22]
[cren-plugin-ko_KR.zip](https://github.com/guhemama/worpdress-comment-reply-email-notification/files/2346252/cren-plugin-ko_KR.zip)

Thanks for your kind reply 
https://wordpress.org/support/topic/i-made-some-changes-to-source-code-can-i-update-without-any-problem/#post-10652546

I want to share my Korean translation with you.

_If you are wondering about who I am in Wordpress, I am a new Korean member who just got into translation and currently am Project Translation Editor.
https://make.wordpress.org/polyglots/teams/?locale=ko_KR_

Cheers!

**Comment by junglesub** [comment]
[cren-plugin-ko_KR.zip](https://github.com/guhemama/worpdress-comment-reply-email-notification/files/2349046/cren-plugin-ko_KR.zip)
I made one small change.

**Comment by guhemama** [comment]
Thanks!

Gustavo Henrique Mascarenhas Machado

+55 41 99639 3490 | +595 972 448 642 | Skype: guhemamascarenhas |
https://guh.me

Em ter, 4 de set de 2018 10:32, Jungsub Ryoo <notifications@github.com>
escreveu:

**Comment by guhemama** [comment]
Thanks for your contribution. I'm merging it today.
