### ISSUE TITLE
Not working on my website using Jorvik theme

### ISSUE THREAD

**Issue by McG77** [guhemama/worpdress-comment-reply-email-notification#25]
Hi, I installed your plugin and had a friend place a comment. I approved it from the back-office - no email sent. I replied via back-office. No email sent. I replied directly on the website - no email received by commenter. missionarynightmare.com 
The comment was placed on this article: https://missionarynightmare.com/jou-hofsaak

**Comment by guhemama** [comment]
Hey,

Are you using a plugin to send emails via SMTP? Usually the problem is with Wordpress, since it sends emails via PHP's mail() function.

**Comment by McG77** [comment]
No, I have no email plug-ins installed except yours.

**Comment by guhemama** [comment]
In this case I suggest installing the Post SMTP plugin: you will be able to setup better email deliverability methods (SMTP), and also debug the existing setup.

https://wordpress.org/plugins/post-smtp/
