### ISSUE TITLE
Setting wp_mail_content_type just for emails sent by this plugin

### ISSUE THREAD

**Issue by makeworthymedia** [guhemama/worpdress-comment-reply-email-notification#5]
Thanks so much for writing this plugin! It was exactly what I was looking for and replaces an older plugin that is no longer supported. I had one suggestion though. When I activated this plugin it started messing up the formatting of regular email notifications the post's author would get since those notifications were formatted to be in "text/plain" format but the plugin updated the default format to be "text/html." I was able to fix this by moving the "wp_mail_content_type" filter into the cren_comment_notification function, and then using a remove_filter call to turn it off after the email had been sent.

**Comment by guhemama** [comment]
Thanks for the great feedback! :smile: 
This is indeed a bug, and your suggested fix is great. I will release a bug fix.
